spring.application.name=crud-app-with-security

# server configuration
server.port=8080

# database configuration
#spring.datasource.url=jdbc:h2:mem:crud_app_db
spring.datasource.url=jdbc:h2:file:./crud_app_db

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
#
# h2 DB Configurations
spring.h2.console.enabled=true
spring.h2.console.path=/auth/h2-console
#
## JPA Hibernate Configurations
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true


# Jwt Configurations

#default for local
app.jwt.secret=${JWT_SECRET}
# 24 hours in milliseconds
app.jwt.expiration=86400000

# jackson config
spring.jackson.deserialization.fail-on-unknown-properties=true
#spring.jackson.default-property-inclusion=non_null