name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        # actions/checkout@v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up JDK 21
        # actions/setup-java@v4.5.0
        uses: actions/setup-java@387ac29b308b003c05baef7110591452499a4ee2
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Links to distributionManagement in pom.xml
          settings-path: ${{ github.workspace }}
          cache: maven # Added caching for efficiency

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}